# Generated by Django 4.2.4 on 2023-08-09 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailitem',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='working_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 9, 15, 35, 18, 846986, tzinfo=datetime.timezone.utc), verbose_name='工作日期'),
        ),
    ]
