# Generated by Django 4.2.4 on 2023-08-09 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_workrecord_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='end_time',
            field=models.DateTimeField(verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='start_time',
            field=models.DateTimeField(verbose_name='起始時間'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='working_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 9, 16, 18, 27, 941256, tzinfo=datetime.timezone.utc), verbose_name='工作日期'),
        ),
    ]
