# Generated by Django 4.2.4 on 2023-08-09 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_detailitem_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='end_time',
            field=models.TimeField(verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='start_time',
            field=models.TimeField(verbose_name='起始時間'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='working_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 9, 15, 40, 44, 126894, tzinfo=datetime.timezone.utc), verbose_name='工作日期'),
        ),
    ]
